# Generated by Django 3.1.7 on 2022-08-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(max_length=100)),
                ('ticket_content', models.TextField()),
                ('ticket_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
